require("custom.plugins-setup")
require("custom.core.options")
require("custom.core.colorscheme")

require("custom.plugins.comment")
require("custom.plugins.nvim-tree")
require("custom.plugins.lualine")
require("custom.plugins.bufferline")
require("custom.plugins.telescope")
require("custom.plugins.nvim-cmp")
require("custom.plugins.lsp.mason")
require("custom.plugins.lsp.lspsaga")
require("custom.plugins.lsp.lspconfig")
require("custom.plugins.lsp.null-ls")
require("custom.plugins.autopairs")
require("custom.plugins.treesitter")
require("custom.plugins.gitsigns")
require("custom.plugins.undo-tree")
require("custom.plugins.indent-blankline")

require("custom.core.keymaps")
